// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transactions.Data;

#nullable disable

namespace Transactions.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    [Migration("20240417183602_V2")]
    partial class V2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Transactions.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Balance = 1000.00m,
                            Currency = "EUR",
                            UserName = "Alice"
                        },
                        new
                        {
                            Id = "2",
                            Balance = 2000.00m,
                            Currency = "USD",
                            UserName = "Bob"
                        },
                        new
                        {
                            Id = "3",
                            Balance = 3000.00m,
                            Currency = "CAD",
                            UserName = "Charlie"
                        },
                        new
                        {
                            Id = "4",
                            Balance = 4000.00m,
                            Currency = "USD",
                            UserName = "Dave"
                        },
                        new
                        {
                            Id = "5",
                            Balance = 5000.00m,
                            Currency = "EUR",
                            UserName = "Eve"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
